Improving READ.md
Cantera/cantera-website pull request #122
Opened 2020-10-01 08:08 UTC by aman5062

2020-10-02 15:50 UTC, decaluwe requested changes
Thanks, @aman5062.  I like the addition of "How" (as in "How to"), but would replace the question mark with a colon, in all cases.

Thanks again!

2020-10-02 15:50 UTC, decaluwe commented on README.md
> +## How to build the website?
I would remove the question mark, here.

2020-10-02 15:50 UTC, decaluwe commented on README.md
> +## How to build the website?
```suggestion
## How to build the website:
```

2020-10-02 15:50 UTC, decaluwe commented on README.md
> +## How to add a language of examples?
```suggestion
## How to add a language of examples:
```

2020-10-02 15:50 UTC, decaluwe commented on README.md
> +## How to add an example category for Jupyter or Python?
```suggestion
## How to add an example category for Jupyter or Python:
```

2020-10-02 15:50 UTC, decaluwe commented on README.md
> +## How to add a version's release notes?
```suggestion
## How to add a version's release notes:
```

2020-10-15 16:22 UTC, bryanwweber commented
@aman5062 I'm going to close this since you didn't respond to the comments after a few weeks. Thanks for your help, if you want to modify the suggestions that @decaluwe mentioned, then please feel free to reopen the pull request.

2020-10-16 02:21 UTC, aman5062 commented
Thanks

2021-01-15 20:47 UTC, closed without merging