Add YAML-based ThermoBuild tutorial
Cantera/cantera-website pull request #161
Opened 2021-11-20 17:02 UTC by speth

* Add updated NASA ThermoBuild tutorial based on YAML format. The old version of this is embedded in the CTI tutorial and will get deleted when those docs go away.
* Fix the URL for ThermoBuild, which has apparently changed.
* Specify use of the `ruamel.yaml` conda package instead of `ruamel_yaml`. This parallels a change made in Cantera/cantera#1140.

2021-11-21 03:15 UTC, bryanwweber commented
The `ruamel.yaml` changes are related to this issue: https://github.com/conda-forge/ruamel_yaml-feedstock/issues/1 and this issue: https://github.com/conda-forge/ruamel.yaml-feedstock/issues/7 Unfortunately, the relevant discussion and history on the `ruamel-yaml` project has been deleted, since Bitbucket decided to stop supporting Mercurial and the author moved the code to Sourceforge.

2021-11-22 14:46 UTC, ischoegl reviewed
Just looked at the rendered output based on the CI artifacts, and the tutorial looks good to me (although I haven't tested it).

2022-01-20 17:10 UTC, ischoegl requested changes
@speth ... I ran through your instructions and most of this is straight-forward. I did find some minor points though.

2022-01-27 03:10 UTC, speth commented
Thanks for catching those issues, @ischoegl. I think this is good to go now.

2022-01-27 04:10 UTC, merged