Add mole reactor science pages
Cantera/cantera-website pull request #253
Opened 2023-08-02 01:46 UTC by anthony-walker

The mole based reactors are currently undocumented in the science pages. This adds science pages for them. It is my intention to more content in regards to preconditioning. This closes #244.

2023-08-02 19:48 UTC, speth requested changes
Thanks @anthony-walker. I think this mostly looks good. I have a few suggestions. Please note that most of these comments apply across multiple reactor variants.

2023-08-02 19:48 UTC, speth commented on pages/science/reactors/constpresmolereactor.rst
> +A Constant Pressure Reactor is defined by the two state variables:
```suggestion
A Constant Pressure Mole Reactor is defined by the two state variables:
```

2023-08-02 19:48 UTC, speth commented on pages/science/reactors/constpresmolereactor.rst
> +   \tag{2}
I think you're missing $k$ subscripts on all the $\dot{n}$ terms. Also, I don't think there's a formula for $n_{wall}$ given anywhere. On the parent page for reactors, the walls section provides only the related formula for $m_{k,wall}$.

2023-08-02 19:48 UTC, speth commented on pages/science/reactors/idealgasconstpresmolereactor.rst
> +
For consistency with the RHS/LHS separation that we use, I would suggest keeping the $\sum_k n_k \bar{c}_{p,k}$ on the left hand side.

2023-08-04 01:25 UTC, anthony-walker commented
@speth Thank you for the quick turn around on review. I made the changes you suggested and I added some basic discussion and an example about preconditioning in the `CVODES` page.

2023-08-04 14:20 UTC, speth approved these changes
Thanks, @anthony-walker, this looks good to me.

2023-08-04 14:20 UTC, merged